### ISSUE TITLE
Export of multiple dashboards at once fails the first time

### ISSUE THREAD

**Issue by sstarcher** [utkarshcmu/wizzy#41] opened 2016-12-20 14:05 UTC
If the dashboards are not created in sequential order they will fail.  I attempted to create 4 dashboards at once.

```
wizzy export datasources
Output:
{
  "id": 1,
  "message": "Datasource added"
}
✔ Datasource export successful.
Output:
Grafana API response status code = 500
No error body from Grafana API.
✘ Datasource export failed.
Output:
Grafana API response status code = 500
No error body from Grafana API.
✘ Datasource export failed.
Output:
{
  "id": 2,
  "message": "Datasource added"
}
✔ Datasource export successful.
```

**Comment by utkarshcmu** [comment] 2016-12-20 17:37
The issue is - https://github.com/go-xorm/xorm/issues/161

And if you see grafana server logs, you must see the following:
```
EROR[12-20|09:36:40] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=PUT path=/api/datasources/7 status=500 remote_addr=127.0.0.1 time_ms=39ns size=41
```

**Comment by utkarshcmu** [comment] 2016-12-21 16:08
This should be fixed now!

**Closed by utkarshcmu** 2016-12-21 16:08 UTC
Labels: grafana dependency
