### ISSUE TITLE
Wizzy 0.5.3 error

### ISSUE THREAD

**Issue by sstarcher** [utkarshcmu/wizzy#68] opened 2017-01-12 19:11 UTC
I'm getting this with 0.5.3 and 0.5.2.  Working fine with 0.5.1

```
 wizzy export datasources
/usr/local/lib/node_modules/wizzy/src/commands.js:76
			grafana.export(_.drop(commands));
			       ^

TypeError: Cannot read property 'export' of undefined
    at Commands.instructions (/usr/local/lib/node_modules/wizzy/src/commands.js:76:11)
    at Command.listener (/usr/local/lib/node_modules/wizzy/node_modules/commander/index.js:301:8)
    at emitOne (events.js:96:13)
    at Command.emit (events.js:188:7)
    at Command.parseArgs (/usr/local/lib/node_modules/wizzy/node_modules/commander/index.js:617:12)
    at Command.parse (/usr/local/lib/node_modules/wizzy/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/wizzy/src/index.js:14:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by utkarshcmu** [comment] 2017-01-12 21:46
will take a look and fix it by today, thanks for reporting

**Comment by utkarshcmu** [comment] 2017-01-12 21:54
Try running `wizzy init` before running this command as I am not able to reproduce this. :(

**Comment by utkarshcmu** [comment] 2017-01-12 21:57
Also, I will put in more testing so that we test before releasing....

**Comment by sstarcher** [comment] 2017-01-13 13:00
```
➜  grafana-dashboards git:(master) npm install -g wizzy@0.5.3
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/usr/local/bin/wizzy -> /usr/local/lib/node_modules/wizzy/src/index.js
/usr/local/lib
└── wizzy@0.5.3

➜  grafana-dashboards git:(master) wizzy init
✔ conf dir already exists.
✔ conf file already exists.
✔ dashboards dir already exists.
✔ rows dir already exists.
✔ panels dir already exists.
✔ temp-vars dir already exists.
✔ dash-tags dir created.
✔ orgs dir already exists.
✔ datasources dir already exists.
✔ conf/dash-list.json file created.
✔ dash-list file created under conf directory.
✔ wizzy successfully initialized.
➜  grafana-dashboards git:(master) wizzy export datasources
/usr/local/lib/node_modules/wizzy/src/commands.js:76
			grafana.export(_.drop(commands));
			       ^

TypeError: Cannot read property 'export' of undefined
    at Commands.instructions (/usr/local/lib/node_modules/wizzy/src/commands.js:76:11)
    at Command.listener (/usr/local/lib/node_modules/wizzy/node_modules/commander/index.js:301:8)
    at emitOne (events.js:96:13)
    at Command.emit (events.js:188:7)
    at Command.parseArgs (/usr/local/lib/node_modules/wizzy/node_modules/commander/index.js:617:12)
    at Command.parse (/usr/local/lib/node_modules/wizzy/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/wizzy/src/index.js:14:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by sstarcher** [comment] 2017-01-13 13:09
The check for ` components.checkDirsStatus()` is checking that `conf/dash-list.json` exists which is not created by `wizzy init`.  Since I did not have dash-list.json created neither grafana or s3 would load which is what caused my error.

**Comment by utkarshcmu** [comment] 2017-01-13 17:40
I'll fix it asap... and release 0.5.4 and make wizzy more flexible in terms of the code it has... so that we do not face this issue again...

**Comment by utkarshcmu** [comment] 2017-01-18 09:53
Fixed in master!

**Closed** 2017-01-18 09:53 UTC
Labels: bug
